


const filteredArray = ({ arr, arr2, key }) => {
  const filterArr = arr.filter(function (array_el) {
    return (
      arr2.filter(function (anotherOne_el) {
        return anotherOne_el[key] === array_el[key];
      }).length === 0
    );
  });
  return filterArr;
};

const sortArray = ({ arr, key }) => {
  return arr.sort((a, b) => (a[key] > b[key] ? 1 : b[key] > a[key] ? -1 : 0));
};
const trades = {
  mainTeam: {
    id: 8,
    name: "Bears",
    adp: 1,
    index: 8,
    logo: "https://api.nfldraftfanatics.com/media/chi.png",
    selection: 1,
    picks: [
      {
        pick: 1,
        value: "3000.0",
        index: 1,
      },
      {
        pick: 22,
        value: "370.0",
        index: 53,
      },
      {
        pick: 1,
        value: "270.0",
        index: 64,
      },
      {
        pick: 2,
        value: "112.0",
        index: 97,
      },
      {
        pick: 32,
        value: "45.0",
        index: 127,
      },
      {
        pick: 3,
        value: "42.0",
        index: 130,
      },
      {
        pick: 23,
        value: "29.8",
        index: 150,
      },
      {
        pick: 3,
        value: "12.2",
        index: 194,
      },
    ],
    picksYears: [
      {
        round: "R1",
        id: 1460,
        value: "3000.0",
      },
      {
        round: "R2",
        id: 1512,
        value: "370.0",
      },
      {
        round: "R3",
        id: 1523,
        value: "270.0",
      },
      {
        round: "R4",
        id: 1556,
        value: "112.0",
      },
      {
        round: "R4",
        id: 1586,
        value: "45.0",
      },
      {
        round: "R5",
        id: 1589,
        value: "42.0",
      },
      {
        round: "R5",
        id: 1609,
        value: "29.8",
      },
      {
        round: "R7",
        id: 1653,
        value: "12.2",
      },
    ],
    pick: [
      {
        pick: 1,
        value: "3000.0",
        index: 1,
      },
      {
        pick: 22,
        value: "370.0",
        index: 53,
      },
      {
        pick: 1,
        value: "270.0",
        index: 64,
      },
    ],
    pickYear: [
      {
        round: "R2",
        id: 1512,
        value: "370.0",
      },
      {
        round: "R3",
        id: 1523,
        value: "270.0",
      },
    ],
    players: [
      {
        player: "Select Players",
        position: "",
      },
      {
        id: 1,
        value: 285,
        position: "FS",
        player: "Eddie Jackson",
        round: 8,
      },
      {
        id: 2,
        value: 501,
        position: "G",
        player: "Cody Whitehair",
        round: 8,
      },
      {
        id: 3,
        value: 285,
        position: "DT",
        player: "Justin Jones",
        round: 8,
      },
      {
        id: 4,
        value: 285,
        position: "G",
        player: "Lucas Patrick",
        round: 8,
      },
      {
        id: 5,
        value: 1500,
        position: "QB",
        player: "Justin Fields",
        round: 8,
      },
      {
        id: 6,
        value: 26,
        position: "K",
        player: "Cairo Santos",
        round: 8,
      },
      {
        id: 7,
        value: 131,
        position: "DE",
        player: "Al-Quadin Muhammad",
        round: 8,
      },
      {
        id: 8,
        value: 131,
        position: "TE",
        player: "Cole Kmet",
        round: 8,
      },
      {
        id: 9,
        value: 131,
        position: "CB",
        player: "Jaylon Johnson",
        round: 8,
      },
      {
        id: 10,
        value: 131,
        position: "WR",
        player: "Darnell Mooney",
        round: 8,
      },
      {
        id: 11,
        value: 131,
        position: "WR",
        player: "Chase Claypool",
        round: 8,
      },
      {
        id: 12,
        value: 131,
        position: "DE",
        player: "Trevis Gipson",
        round: 8,
      },
      {
        id: 13,
        value: 131,
        position: "CB",
        player: "Kindle Vildor",
        round: 8,
      },
      {
        id: 14,
        value: 131,
        position: "QB",
        player: "Trevor Siemian",
        round: 8,
      },
      {
        id: 15,
        value: 131,
        position: "G",
        player: "Teven Jenkins",
        round: 8,
      },
      {
        id: 16,
        value: 131,
        position: "CB",
        player: "Kyler Gordon",
        round: 8,
      },
      {
        id: 17,
        value: 131,
        position: "RT",
        player: "Alex Leatherwood",
        round: 8,
      },
      {
        id: 18,
        value: 131,
        position: "S",
        player: "Jaquan Brisker",
        round: 8,
      },
    ],
    player: {
      id: 1,
      value: 285,
      position: "FS",
      player: "Eddie Jackson",
      round: 8,
    },
  },
  myTeam: {
    id: 2,
    name: "Texans",
    adp: null,
    index: 2,
    logo: "https://api.nfldraftfanatics.com/media/hou.png",
    selection: 2,
    picks: [
      {
        pick: 2,
        value: "2600.0",
        index: 2,
      },
      {
        pick: 12,
        value: "1200.0",
        index: 12,
      },
      {
        pick: 2,
        value: "580.0",
        index: 33,
      },
      {
        pick: 2,
        value: "265.0",
        index: 65,
      },
      {
        pick: 10,
        value: "225.0",
        index: 73,
      },
      {
        pick: 1,
        value: "116.0",
        index: 96,
      },
      {
        pick: 2,
        value: "43.0",
        index: 129,
      },
      {
        pick: 14,
        value: "20.6",
        index: 173,
      },
      {
        pick: 24,
        value: "16.6",
        index: 183,
      },
      {
        pick: 29,
        value: "14.6",
        index: 188,
      },
      {
        pick: 30,
        value: "14.2",
        index: 189,
      },
      {
        pick: 22,
        value: "4.6",
        index: 213,
      },
    ],
    picksYears: [
      {
        round: "R1",
        id: 1461,
        value: "2600.0",
      },
      {
        round: "R1",
        id: 1471,
        value: "1200.0",
      },
      {
        round: "R2",
        id: 1492,
        value: "580.0",
      },
      {
        round: "R3",
        id: 1524,
        value: "265.0",
      },
      {
        round: "R3",
        id: 1532,
        value: "225.0",
      },
      {
        round: "R4",
        id: 1555,
        value: "116.0",
      },
      {
        round: "R5",
        id: 1588,
        value: "43.0",
      },
      {
        round: "R6",
        id: 1632,
        value: "20.6",
      },
      {
        round: "R6",
        id: 1642,
        value: "16.6",
      },
      {
        round: "R6",
        id: 1647,
        value: "14.6",
      },
      {
        round: "R6",
        id: 1648,
        value: "14.2",
      },
      {
        round: "R7",
        id: 1672,
        value: "4.6",
      },
    ],
    pick: [
      {
        pick: 2,
        value: "2600.0",
        index: 2,
      },
      {
        pick: 12,
        value: "1200.0",
        index: 12,
      },
      {
        pick: 2,
        value: "580.0",
        index: 33,
      },
    ],
    pickYear: [
      {
        round: "R1",
        id: 1471,
        value: "1200.0",
      },
      {
        round: "R1",
        id: 1461,
        value: "2600.0",
      },
    ],
    players: [
      {
        player: "Select Players",
        position: "",
      },
      {
        id: 161,
        value: 131,
        position: "LT",
        player: "Laremy Tunsil",
        round: 2,
      },
      {
        id: 162,
        value: 131,
        position: "WR",
        player: "Brandin Cooks",
        round: 2,
      },
      {
        id: 163,
        value: 26,
        position: "RT",
        player: "Tytus Howard",
        round: 2,
      },
      {
        id: 164,
        value: 253,
        position: "DT",
        player: "Maliek Collins",
        round: 2,
      },
      {
        id: 165,
        value: 253,
        position: "CB",
        player: "Derek Stingley Jr.",
        round: 2,
      },
      {
        id: 166,
        value: 26,
        position: "DE",
        player: "Jerry Hughes",
        round: 2,
      },
      {
        id: 167,
        value: 26,
        position: "ILB",
        player: "Christian Kirksey",
        round: 2,
      },
      {
        id: 168,
        value: 26,
        position: "G",
        player: "A.J. Cann",
        round: 2,
      },
      {
        id: 169,
        value: 26,
        position: "K",
        player: "Ka'imi Fairbairn",
        round: 2,
      },
      {
        id: 170,
        value: 26,
        position: "CB",
        player: "Steven Nelson",
        round: 2,
      },
      {
        id: 171,
        value: 26,
        position: "FS",
        player: "Eric Murray",
        round: 2,
      },
      {
        id: 172,
        value: 26,
        position: "CB",
        player: "Desmond King",
        round: 2,
      },
      {
        id: 173,
        value: 26,
        position: "DE",
        player: "Mario Addison",
        round: 2,
      },
      {
        id: 174,
        value: 26,
        position: "OLB",
        player: "Jalen Reeves-Maybin",
        round: 2,
      },
      {
        id: 175,
        value: 26,
        position: "C",
        player: "Justin Britt",
        round: 2,
      },
      {
        id: 176,
        value: 26,
        position: "G",
        player: "Kenyon Green",
        round: 2,
      },
      {
        id: 177,
        value: 26,
        position: "P",
        player: "Cameron Johnston",
        round: 2,
      },
      {
        id: 178,
        value: 26,
        position: "S",
        player: "Jalen Pitre",
        round: 2,
      },
    ],
    player: {
      id: 161,
      value: 131,
      position: "LT",
      player: "Laremy Tunsil",
      round: 2,
    },
  },
  mainTeams: [],
  myTeams: [],
  tradesTeams: [
    {
      id: 8,
      name: "Bears",
      adp: 1,
      index: 8,
      logo: "https://api.nfldraftfanatics.com/media/chi.png",
      selection: 1,
    },
    {
      id: 2,
      name: "Texans",
      adp: null,
      index: 2,
      logo: "https://api.nfldraftfanatics.com/media/hou.png",
      selection: 2,
    },
    {
      id: 20,
      name: "Cardinals",
      adp: null,
      index: 21,
      logo: "https://api.nfldraftfanatics.com/media/ari.png",
      selection: 3,
    },
    {
      id: 24,
      name: "Colts",
      adp: null,
      index: 25,
      logo: "https://api.nfldraftfanatics.com/media/ind.png",
      selection: 4,
    },
    {
      id: 4,
      name: "Seahawks",
      adp: null,
      index: 4,
      logo: "https://api.nfldraftfanatics.com/media/sea.png",
      selection: 5,
    },
    {
      id: 3,
      name: "Lions",
      adp: null,
      index: 3,
      logo: "https://api.nfldraftfanatics.com/media/det.png",
      selection: 6,
    },
    {
      id: 14,
      name: "Raiders",
      adp: null,
      index: 15,
      logo: "https://api.nfldraftfanatics.com/media/lv.png",
      selection: 7,
    },
    {
      id: 1,
      name: "Falcons",
      adp: null,
      index: 1,
      logo: "https://api.nfldraftfanatics.com/media/atl_1.png",
      selection: 8,
    },
    {
      id: 7,
      name: "Panthers",
      adp: null,
      index: 7,
      logo: "https://api.nfldraftfanatics.com/media/car.png",
      selection: 9,
    },
    {
      id: 18,
      name: "Eagles",
      adp: null,
      index: 19,
      logo: "https://api.nfldraftfanatics.com/media/phi.png",
      selection: 10,
    },
    {
      id: 16,
      name: "Titans",
      adp: null,
      index: 17,
      logo: "https://api.nfldraftfanatics.com/media/ten.png",
      selection: 11,
    },
    {
      id: 5,
      name: "Jets",
      adp: null,
      index: 5,
      logo: "https://api.nfldraftfanatics.com/media/nyj.png",
      selection: 13,
    },
    {
      id: 15,
      name: "Patriots",
      adp: null,
      index: 16,
      logo: "https://api.nfldraftfanatics.com/media/ne.png",
      selection: 14,
    },
    {
      id: 28,
      name: "Packers",
      adp: null,
      index: 29,
      logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      selection: 15,
    },
    {
      id: 32,
      name: "Commanders",
      adp: null,
      index: 11,
      logo: "https://api.nfldraftfanatics.com/media/wsh_5TI9IsB.png",
      selection: 16,
    },
    {
      id: 11,
      name: "Steelers",
      adp: null,
      index: 12,
      logo: "https://api.nfldraftfanatics.com/media/pit.png",
      selection: 17,
    },
    {
      id: 30,
      name: "Buccaneers",
      adp: 15,
      index: 31,
      logo: "https://api.nfldraftfanatics.com/media/tb.png",
      selection: 19,
    },
    {
      id: 22,
      name: "Chargers",
      adp: null,
      index: 23,
      logo: "https://api.nfldraftfanatics.com/media/lac.png",
      selection: 21,
    },
    {
      id: 19,
      name: "Ravens",
      adp: null,
      index: 20,
      logo: "https://api.nfldraftfanatics.com/media/bal.png",
      selection: 22,
    },
    {
      id: 12,
      name: "Vikings",
      adp: null,
      index: 13,
      logo: "https://api.nfldraftfanatics.com/media/min.png",
      selection: 23,
    },
    {
      id: 6,
      name: "Jaguars",
      adp: null,
      index: 6,
      logo: "https://api.nfldraftfanatics.com/media/jax.png",
      selection: 24,
    },
    {
      id: 9,
      name: "Giants",
      adp: null,
      index: 9,
      logo: "https://api.nfldraftfanatics.com/media/nyg.png",
      selection: 25,
    },
    {
      id: 25,
      name: "Cowboys",
      adp: null,
      index: 26,
      logo: "https://api.nfldraftfanatics.com/media/dal.png",
      selection: 26,
    },
    {
      id: 31,
      name: "Bills",
      adp: null,
      index: 32,
      logo: "https://api.nfldraftfanatics.com/media/buf.png",
      selection: 27,
    },
    {
      id: 26,
      name: "Bengals",
      adp: null,
      index: 27,
      logo: "https://api.nfldraftfanatics.com/media/cin.png",
      selection: 28,
    },
    {
      id: 13,
      name: "Saints",
      adp: null,
      index: 14,
      logo: "https://api.nfldraftfanatics.com/media/no.png",
      selection: 29,
    },
    {
      id: 29,
      name: "Chiefs",
      adp: null,
      index: 30,
      logo: "https://api.nfldraftfanatics.com/media/kc.png",
      selection: 31,
    },
    {
      id: 27,
      name: "Rams",
      adp: null,
      index: 28,
      logo: "https://api.nfldraftfanatics.com/media/lar.png",
      selection: 36,
    },
    {
      id: 17,
      name: "Browns",
      adp: null,
      index: 18,
      logo: "https://api.nfldraftfanatics.com/media/cle.png",
      selection: 42,
    },
    {
      id: 33,
      name: "Dolphins",
      adp: 12,
      index: 10,
      logo: "https://api.nfldraftfanatics.com/media/MIA.png",
      selection: 51,
    },
    {
      id: 21,
      name: "Broncos",
      adp: null,
      index: 22,
      logo: "https://api.nfldraftfanatics.com/media/den.png",
      selection: 67,
    },
    {
      id: 23,
      name: "49ers",
      adp: null,
      index: 24,
      logo: "https://api.nfldraftfanatics.com/media/sf.png",
      selection: 146,
    },
  ],
  changeTrades: false,
  acceptTrade: false,
  acceptCount: 10,
  myTradesPlayers: [],
  loading: false,
  historyTrades: [],
  tradePlayerYears: [],
};

function changeTeamInfo({ trades }) {
  
}
changeTeamInfo({ trades });
